GET http://localhost:3000/todos

###
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Learn REST API",
  "completed": false,
  "status": "active"
}

###
PATCH http://localhost:3000/todos/1
Content-Type: application/json

{
  "completed": true
}   
###

DELETE http://localhost:3000/todos/67efb1a47f76c352ed3a13c
